CREATE TABLE IF NOT EXISTS form_submissions (
  id TEXT PRIMARY KEY,
  identity TEXT NOT NULL,
  birth_year TEXT NOT NULL,
  approximate_age INTEGER,
  sex TEXT NOT NULL,
  province_code TEXT,
  province_name TEXT,
  city_code TEXT,
  city_name TEXT,
  county_code TEXT,
  county_name TEXT,
  school_name TEXT NOT NULL,
  school_address TEXT,
  date_start TEXT NOT NULL,
  date_end TEXT,
  experience TEXT,
  headmaster_name TEXT,
  contact_information TEXT NOT NULL,
  scandal TEXT,
  other_notes TEXT,
  lang TEXT NOT NULL,
  source_path TEXT NOT NULL,
  client_ip_hash TEXT,
  user_agent TEXT,
  created_at TEXT NOT NULL
);
